### ISSUE TITLE
Can't find the function "mask_all"

### ISSUE THREAD

**Issue by Archie-qi** [CausalML-Lab/PCMCI-Omega#2]
Hello.
 It seems like you forget to define the function "mask_all" in your code:      "dataframe = pp.DataFrame(data_run, mask= mask_all[i-1][j][N:T,:],datatime = {0:np.arange(len(data_run))}, var_names=var_names) ".

Much appreciate it if you could fix this bug.

**Comment by GaoShan9** [comment]
Got it. I will fix it over this weekend. Thank you for pointing this out!

**Comment by Dpingping** [comment]
Could you please provide “mask_all"? Thank you for your help

**Comment by GaoShan9** [comment]
I am so sorry for the late response. I have solved the "mask_all" issues. Thank you for pointing this out!
